# Generated by Django 5.1.5 on 2025-02-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_verification_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Can view user list"),
                    ("can_blocking_user", "Can blocking user"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
