# Generated by Django 5.1.5 on 2025-02-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
