# Generated by Django 5.1.5 on 2025-02-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0004_mailing_owner_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_disabling_mailing", "Can disabling mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipientmail",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_recipient_mail", "Can view recipient mail")],
                "verbose_name": "Получатель письма",
                "verbose_name_plural": "Получатели писем",
            },
        ),
    ]
