# Generated by Django 5.1.5 on 2025-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0007_mailingattempt_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время последней отправки"),
        ),
    ]
