# Generated by Django 5.1.5 on 2025-02-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0008_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disabling_mailing", "Can disabling mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipientmail",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Получатель письма",
                "verbose_name_plural": "Получатели писем",
            },
        ),
    ]
