# Generated by Django 5.1.5 on 2025-02-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0010_alter_mailing_options_alter_recipientmail_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipientmail",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Получатель письма",
                "verbose_name_plural": "Получатели писем",
            },
        ),
    ]
